README.md

that makes the in container edits obsolet and the config file can be mapped in from a distributed fs to example

(documentation) volume opions for config file

---

Dockerfile
README.md

As already discussed internally, the current image on the hub is named wrong ([mashape/docker-kong](https://registry.hub.docker.com/u/mashape/docker-kong/)).
Since there is no way to rename an image, I created [mashape/docker](https://registry.hub.docker.com/u/mashape/kong/).
Instead of having to use the image as:
```shell
$ docker pull mashape/docker-kong
```
This one will would feel nicer:
```shell
$ docker pull mashape/kong
```
**Maybe give a thumb up if you want to drop mashape/docker-kong in favour of mashape/docker on the hub.**
This PR also proposes a rewrite of the usage of this image, as well as a slight refactor of the said image:
- It uses a [Volume](https://docs.docker.com/userguide/dockervolumes/) for the configuration
- It is more readable (as advised by docker's …

[refactor] nicer image (VOLUME/style) + docs

---

README.md

`exec` is for running commands inside the existing container, `run` would actually create a new container and run the `kong reload` there ... which likely will fail like this:
~~~~
$ docker run -it kong kong reload
Unable to find image 'kong:latest' locally
Trying to pull repository docker.io/kong ... not found
Error: image library/kong:latest not found
$ docker run -it mashape/kong kong reload
[INFO] Using configuration: /etc/kong/kong.yml
[ERR] Could not reload: Kong is not running.
~~~~
(The first error would be because `run` wants an image name, not a container name; the second one then uses a suitable image name, but that one just doesn't have a kong running)

Use docker `exec` instead of `run`

---

compose/docker-compose.yml

This following recurring log was a hint that some recurrent task would not use
an existing PostgreSQL user:
kong-database_1   | FATAL:  role "root" does not exist
The proposed fix ensures `healthcheck` is always using the default
`postgres` user instead of `$(whoami)`.
We switch `CMD-SHELL` to `CMD` so we can pass arguments to `pg_isready`
in subsequent elements of the Array.
It seems the shell does not inherit the environment variables passed to
the `environment` attribute, so using `$POSTGRES_USER` did not work in
my initial tests.

fix: use postgres user for kong-database healthcheck

---

alpine/Dockerfile

`apk` provides a handy `--no-cache` flag that [disables the global cache][1]. This is favored over `rm -rf /var/cache/apk/*`
Replaces the `MAINTAINER` instruction, which has been [deprecated][2], with a `LABEL`.
[1]: https://github.com/gliderlabs/docker-alpine/tree/master#usage
[2]: https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

Disable local cache

---

centos/Dockerfile

The current 0.11.2 commit sha1
(2ed0fad88ed81623ea4afb2111033a9d87f3c03c) still uses the previous rpm
path (in ?file_path).
The purpose of this commit is to produce a new commit sha1 we can make
the 0.11 and 0.11.2 DockerHub tags point to.

fix(centos) create 0.11.2 sha with proper rpm path

---

alpine/Dockerfile

without curl, when we run docker-compose up, it will show errors like /bin/sh: curl: not found

add curl into the alpine kong image

---

alpine/Dockerfile

Use `https` in APK repositories.

feat(alpine) use https repositories

---

alpine/Dockerfile
centos/Dockerfile

Both images verified locally with:
```
$ docker run -ti --rm kong-alpine:0.14.0rc2 sh
/ # kong version
0.14.0rc2
/ # exit
```

chore(*) bump to Kong CE 0.14.0rc2

---

alpine/docker-entrypoint.sh
centos/docker-entrypoint.sh

Instead, let's explicitely note that our branch should execute for both
`start` and `restart`.
This fix ensures that the CLI control commands behave the same way as a
host installation, with a few containerized-specific changes that is:
* `start` invokes `prepare` and guarantees `prepare` is called, and
spawns Nginx in the foreground.
* `restart` behaves the same as `start` when called while Kong is not
running. Calling `restart` on a running Kong container causes it to
terminate, which is expected behavior.
* `reload` on a running container respawn worker processes. If called on
a container not running Kong, it should not error out on non-existing
prefixes. The prefix is thus always created as per the `KONG_PREFIX` env
variable, or the `/usr/local/kong` default.
* `stop` behaves …

fix(*) avoid using =~ in bourne shell

---

alpine/Dockerfile
centos/Dockerfile
legacy/Dockerfile
rhel/Dockerfile

From OpenShift [docs](https://docs.openshift.org/3.9/creating_images/guidelines.html#use-uid):
> By default, OpenShift Origin runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node.
I've added small changes, so Kong could be run on OpenShift out of box.
Please also add those changes to Enterprise version.

Added support for OpenShift

---

alpine/Dockerfile
alpine/docker-entrypoint.sh
centos/Dockerfile
centos/docker-entrypoint.sh
rhel/Dockerfile

moves setcap out of Dockerfile and into the docker entrypoint's

fix(setcap)

---

centos/Dockerfile
centos/docker-entrypoint.sh

Tested locally:
```
docker build --no-cache -t kong:centosfix .
export KONG_DOCKER_TAG=kong:centosfix
cd ../compose
docker-compose up -d
docker-compose logs kong
docker-compose exec kong ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
kong         1  1.0  0.2 266504 18740 ?        Ss   18:15   0:00 nginx: master p
kong        37  0.0  0.4 285084 33700 ?        S    18:15   0:00 nginx: worker p
kong        38  0.0  0.4 285084 33548 ?        S    18:15   0:00 nginx: worker p
root        39  0.0  0.0  51752  3484 ?        Rs+  18:16   0:00 ps aux
```
Manual Test Steps:

fix(centos) centos doesn't have su-exec

---

alpine/Dockerfile
centos/Dockerfile

chore(*) bump to Kong 1.0.1

---

.travis.yml
centos/Dockerfile

Currently CentOS image is unable to install rocks.
The goal is not to make LR fully functional, just enough such that it can install a packed rock.

fix(luarocks) makes LuaRocks usable within the images

---

alpine/docker-entrypoint.sh
centos/docker-entrypoint.sh
rhel/docker-entrypoint.sh

The idea here is to allow additional arguments to pass through to the `kong prepare` command in the entrypoint script without fundamentally changing how the container operates normally.  This way, one could supply flags for verbose/debug output, or a custom nginx template (As is the case for Issue #181 )
I've tested this with the alpine container, but I imagine there wouldn't be any issues with this change for centos/rhel either.

Pass arguments to 'kong prepare' in docker-entrypoint.sh

---

.travis.yml
Makefile
tests.sh

moving the tests to a Makefile / bash script:
- allows for more complicated tests
- makes it CI / CD independent
Also added an additional test to check kong is running as the kong user not as root

feat(tests) moving the tests to a bash script

---

alpine/Dockerfile
centos/Dockerfile

Uses the new travis-ci generated alpine tar which includes a repository rename and package name change

chore(*) bump Kong to 1.1.0

---

alpine/Dockerfile
alpine/docker-entrypoint.sh
centos/Dockerfile
centos/docker-entrypoint.sh
compose/docker-compose.yml
tests.sh

If the kong container is ran with UID 0 (root) assume the desired behaviour is to `su-exec` run Kong with the Kong user (aka 1337) but if it's ran with a non 0 UID assume we want Kong to run as that user.

fix(openshift) openshift runs containers with random UID

---

alpine/Dockerfile
centos/Dockerfile
rhel/Dockerfile

While running in any docker environment like Docker swarm or k8s,
sending a SIGTERM to Kong will drop in-flight requests.
NGINX has decided to keep using SIGTERM because UNIX domain sockets are
not cleaned up properly while using SIGQUIT:
https://github.com/nginxinc/docker-nginx/issues/167
https://github.com/nginxinc/docker-nginx/issues/46
https://trac.nginx.org/nginx/ticket/753
OpenResty, on the other hand, uses SIGQUIT as using UNIX domain sockets
are _usually_ not used with OpenResty:
https://github.com/openresty/docker-openresty/commit/709f99f76af87009f278fdf68684c8712942d44a

fix: send QUIT instead of TERM for graceful shutdown

---

rhel/Dockerfile

chore(rhel) Redhat is updating their base image name

---

compose/docker-compose.yml

As we are already using `networks` so there is no need to use `links` which is also deprecated in the updated version as well as it is also recommended to use networks over links.
Moreover, we are adding the same name as the service name in the alias so it's of no use.

Fixing docker-compose file

---

alpine/Dockerfile
centos/Dockerfile
rhel/Dockerfile
ubuntu/Dockerfile

- bump to Kong 2.0
- ~~bump to kong-build-tools 3.0 - for go smoke tests~~ (skipping that for now - go tests already run for base packages - will come back to it later on)

release: 2.0.0

---

.travis.yml
customize/Dockerfile
tests.sh

`2.0` migrated our docker images to run as user kong but one needs to use root to install plugins etc

fix(customize) use root user to install things

---

.travis.yml
rhel/Dockerfile
update.sh

- redhad requires the version label be populated which we left it blank accidentally
- adjust the travis build to there isn't a deployment per matrix entry

fix(rhel) fix how the RedHat version label is set

---

submit.sh

Didn't catch this change when we merged docker-kong-ee into docker-kong.
The version number moved out of the Dockerfiles into a bash script so `submit.sh` needs to be updated to reflect this change

chore(ci) the version variable no longer lives in the Dockerfile

---

alpine/Dockerfile

closes https://github.com/Kong/kong/issues/5919
```
docker build -t temp .
docker run -it --rm temp ls /etc/ssl/certs/ca-certificates.crt
/etc/ssl/certs/ca-certificates.crt
```

fix(ca-certificates) add ca-certificates to our alpine image

---

alpine/docker-entrypoint.sh
centos/docker-entrypoint.sh
rhel/docker-entrypoint.sh
ubuntu/docker-entrypoint.sh

file_env sets empty envs when is run. This PR adds a safeguard for that case. If `<smth>_FILE` is not set the function does not need to run.

fix(docker) do not set empty vars

---

bintray-release.sh

release script was missing artifact version. We could be clever about it and add the whole logic for extracting it per case on all cases (debian:8 --> jessie) but that seems unecessary as we are only shipping docker images for rhel and centos 7

fix(release) fix missing package version

---

centos/Dockerfile
rhel/Dockerfile
ubuntu/Dockerfile

fpm marks the zlib dependencies therefore it shouldn't be necessary to duplicate that logic in our Dockerfiles

chore(dependencies) infer dependencies from the packages

---

alpine/Dockerfile
ubuntu/Dockerfile

This PR introduces the ability for us to build alpine arm images. The CI has purposefully not been adjusted to keep everything backwards compatible until we have a backlog of alpine arm assets on bintray

chore(arm64) adjust alpine for eventual arm capable builds

---

centos/Dockerfile
rhel/Dockerfile
ubuntu/Dockerfile

During the migration there's a window where the Kong asset may / may not try to `useradd`. We'll allow failures for a period of time but in a future version remove the `useradd` entirely from our docker images

fix(useradd) migrating useradd to after-isntall.sh

---

.travis.yml
compose/docker-compose.yml
tests/01-image.test.sh

kbt tests run the 01 packaging tests then put the assets onto bintray
docker-kong Dockerfile's pull said assets from bintray
let's not re-run the KBT packaging tests. The KBT api tests still has use so going to keep it

fix(tests) dont double test our packages

---

customize/packer.lua
tests/02-customize.test.sh

Besides customizing Kong images by adding pure-Lua plugins in a docker image, this allows to also add plugins/rocks that have c-code. Luarocks makes it sooooo easy, just pack'em and ship'em.
Just rocks that bind to an existing library cannot be added yet, since we have no means of first adding that library yet.

feat(customize) allow rocks with C-code (self contained)

---

Makefile
tests/image.test.sh

Edit to add: there's no historic case defaulting to next would not have worked.
We clone the kong source so we have access to the `.requirements` file.
The requirements file is needed by kong-build-tools to double check the right things got built. However, running the  [01-package test suite](https://github.com/Kong/kong-build-tools/tree/master/test/tests/01-package) on docker-kong CI is largely unecessary (with the exception of the version check as it has been beneficial in the past) as any asset couldn't have been built without already going through the tests.
I think this initially got pinned to `2.1.0-beta.1` because the `$version_given` variable is incorrect for our prereleases.
Future improvements:
- only run the [02-api test …

chore(tests) use the kong source that matches the version we built

---

.travis.yml

CI failures like https://travis-ci.com/github/Kong/docker-kong/jobs/505026062 became very common recently; logging in should ameliorate the state of affairs.

fix(ci) `docker login` to increase hub rate limit

---

.travis.yml

otherwise any community PR's will fail because credentials
are unavailable

fix(ci) only login when secrets are available

---

.travis.yml

the check was incorrect, the variable is always set.
Also changed the order, so the `make build` runs after the docker login, because it also pulls from docker hub

fix(ci) fix the docker-login

---

alpine/Dockerfile

Hello,
We would like to use some native packages that are not available in Alpine 3.11.
Also, it is possible to include this change into Kong v2.3.x?
Thank you!

bump alpine image to 3.13

---

alpine/Dockerfile

https://docs.konghq.com/enterprise/2.4.x/property-reference/#nginx_user
> Note: If the kong user and the kong group are not available, the default user and group credentials will be nobody nobody.
We must create a kong group so that the default `nginx_user` is used. This is already the case in Docker CentOS, for example, but not in Alpine.
Alpine:
```
$ id
uid=100(kong) gid=65533(nogroup) groups=65533(nogroup)
```
CentOS:
```
$ id
uid=1000(kong) gid=1000(kong) groups=1000(kong)
```

fix(alpine) create a system kong group

---

compose/docker-compose.yml

Fixes this issue when trying `docker-compose up`:
`* 'Deploy.Resources.Limits.cpus' expected type 'string', got unconvertible type 'int', value: '2'`

CPUs should be string, not int

---

submit.sh

Ensure major releases automation adds arm64 tag to alpine image. Will help avoid issues like https://github.com/docker-library/official-images/pull/10737 in the future.

chore(automation) add arm64v8 tag to automation

---

submit.sh

Previously, the output would be:
```
diff --git a/library/kong b/library/kong
index 7b1cdf413..c4198b673 100644
--- a/library/kong
+++ b/library/kong
@@ -20,6 +20,24 @@ GitFetch: refs/tags/2.6.0
Directory: centos
Architectures: amd64
+Tags: 2.6.0-alpine, 2.6.0, 2.6
+GitCommit: 76ba9c46dd932e518016d48a8414d7af185c2a76
+GitFetch: refs/tags/2.6.0
+Directory: alpine
+Architectures: amd64, arm64v8
+
+Tags: 2.6.0-ubuntu, 2.6-ubuntu
+GitCommit: 76ba9c46dd932e518016d48a8414d7af185c2a76
+GitFetch: refs/tags/2.6.0
+Directory: ubuntu
+Architectures: amd64, arm64v8
+
+Tags: 2.6.0-centos, 2.6-centos
+GitCommit: 76ba9c46dd932e518016d48a8414d7af185c2a76
+GitFetch: refs/tags/2.6.0
+Directory: centos
+Architectures: amd64
+
+ Tags: 2.5.1-alpine, 2.5.1, 2.5
Tags: 2.5.1-alpine, 2.5.1, 2.5, alpine, latest …
```

chore(submit) avoid dupe previous version tags

---

centos/Dockerfile

Solves for:
```
docker run --rm -v /var/cache/yum:/var/cache/yum -it centos:8 /bin/bash
[root@786d0bc5e1a6 /]# yum update
Failed to set locale, defaulting to C.UTF-8
CentOS Linux 8 - AppStream                                                                                                                                                                                                                                                                                                                                                                                                                                218  B/s |  38  B     00:00
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

fix(centos): centos hacks so we can continue to build for customers that require these

---

centos/Dockerfile
centos/docker-entrypoint.sh

kong-build-tools recycles the `centos/Dockerfile` for testing any rpm asset including amazonlinux2 for example.
Recreating the Dockerfile and entrypoint.sh but leaving this out of CI and out of our official docker library submissions so it doesn't cause release / ci failures
CI was previously setup [here](https://github.com/Kong/docker-kong/commit/c32a80c3dd332d096d1a6461d2816ead344d43c5#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88)
official submissions were previously setup [here](https://github.com/Kong/docker-kong/commit/c32a80c3dd332d096d1a6461d2816ead344d43c5#diff-0b3fd39710963fab4901895867a84a3589ed6c62d4d7493629ba44b581ff4653)

fix(centos): kbt currently depends on the centos Dockerfile existing

---

compose/docker-compose.yml

Platform selection in docker-compose.yaml is preventing initialization on amd64 platforms.
Originated in PR #528 
Fixes #567

fix(config) removes platform from service

---

Makefile
ubuntu/Dockerfile
update.sh

- Ensure architecture is parameterized, so both arm64 and amd64 images are built
- Ensure same kbt version as defined in kong/kong for a particular version is used here (they must match, mostly for testing purposes)
- Ensure shasum is checked for both arm64 and amd64 in the Ubuntu dockerfile
- Update automation (`update.sh`) to account for arm64 on Ubuntu

fix(ubuntu) fixes

---

Dockerfile.apk
Dockerfile.deb
Dockerfile.rpm
alpine/Dockerfile
centos/Dockerfile
ubuntu/Dockerfile

This uses the new `docker@` alias so that we can more faithfully follow up on feedback re: our containers.
This PR only targets dockerfiles NOT covered by a similar commit on https://github.com/Kong/docker-kong/pull/576 (https://github.com/Kong/docker-kong/pull/576/commits/7e60a40a6995ad71cf6b8996a938cc5aa5b978f3)

chore(non-rhel): unify maintainer to docker@

---

Dockerfile.apk
Dockerfile.deb
Dockerfile.rpm
Makefile
build_your_own_images.md

We expect slim images to resolve most of the issues around security scans that pick up non-executable dependencies in our docker images. However, some users will need or want to build Docker images that contain Kong Gateway using their own base images.

(feat): [ENGEN-638] User docs on how to build docker images that contain Kong gateway

---

Dockerfile.apk

We've built openssl ourselves since around ~2.x so I can't see why this is still required

fix(dependency): remove openssl since we build ourselves

---

customize/packer.lua

getting the delta of installed rocks is no longer necessary since we copy the entire rocks-tree over

chore(customize) remove dead code

---

Dockerfile.apk
Dockerfile.deb
Dockerfile.rpm
build_your_own_images.md
customize/Dockerfile

The `kong health` can get expensive to execute too frequently, this PR reduces the frequency it is called by default. It also sets `KONG_PREFIX` `ARG` and `ENV` variables, so the `kong health` command does not need to load the config file to find the Nginx prefix.
FTI-4452

perf(Dockerfile): reduce the HEALTHCHECK frequency

---

docker-entrypoint.sh
ubuntu/docker-entrypoint.sh

This change adds a clean-up step to remove all sockets that a previous Kong run may have left in $PREFIX directory.
Dangling unix sockets have been a pain point in recent Kong versions and was dealt in traditional Kong in Kong/kong#9254, but the `kong` script is not called when starting Kong inside a container, so a similar change to `docker-entrypoint.sh` was added here. 
FTI-4525

fix(docker-entrypoint): clean-up dangling unix sockets

---

Dockerfile.apk
Dockerfile.deb
Dockerfile.rpm
build_your_own_images.md
customize/Dockerfile

Use the `kong-health` standalone script to check container health, avoiding config parsing overhead on `kong health`.
KAG-263
FTI-4452

feat(Dockerfile) use kong-health to check container health

---

Dockerfile.apk
Dockerfile.deb
Dockerfile.rpm
customize/Dockerfile

This change contains cherry-picks from #599 and #621, increasing the period the health-check script is called and using the new `kong-health` script.
FTI-4452
KAG-263

feat(Dockerfile): reduce container health-check overhead

---

docker-entrypoint.sh
ubuntu/docker-entrypoint.sh

On some older kernels (below 4.2), executing `ln -sf /dev/stdout /tmp/access.log` multiple times will only work the first time. This is because those kernels have a bug that misleads `openat()` to recognize `/dev/stdout` as a directory, leading to `ln` does not able to overwrite the existing files.
This can lead to that once the container is started, it will continue to fail when restarting afterward due to the docker entrypoint does not execute properly.
Kernel `3.10`:
```
$ uname -a
Linux KONG 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ 
$ docker run -it --privileged ubuntu:22.04 bash
root@03d0dfc6bb90:/# 
root@03d0dfc6bb90:/# ln -s /dev/stdout /tmp/access.log
root@03d0dfc6bb90:/# ln -s /dev/stdout /tmp/access.log
ln: failed to create …
```

fix(docker): add -n option to avoid ln failing to overwrite the existing symbolic link file

---

Dockerfile.apk
Dockerfile.deb
Dockerfile.rpm
ubuntu/Dockerfile

Versions of Kong built with Bazel include the symbolic links to /usr/local/bin which made the Dockerfiles fail.
KAG-817

fix(*): use `ln -sf` to overwrite symlink if it exists

---

Dockerfile.apk
Dockerfile.deb
Dockerfile.rpm
Makefile
README.md
build_your_own_images.md
docker-entrypoint.sh
ubuntu/Dockerfile
ubuntu/docker-entrypoint.sh
update.sh

Reverts Kong/docker-kong#657
Several problems with this approach:
* The general approach is still under discussion in https://github.com/docker-library/official-images/issues/14888
* Kong/docker-kong#657 should be modifying the KONG_VERSION variable when updating to a new version using `update.sh`
* Kong/docker-kong#657 was missing changing the RPM docker image in `update.sh`

Revert "chore(*): make this repo a thin wrapper of Kong docker images"

---

compose/docker-compose.yml

This patch enables Kong Manager by default and binds it to the same interfaces as Kong's Admin API by default.

feat: enable and bind to localhost for Admin UI

---

ubuntu/Dockerfile

Hi,
This pull request includes several small improvements for the Dockerfile, which should help improve the security of container and reduce the risk of potential attacks.
The following changes have been made:
- I added `--no-install-recommends` to remove unnecessary `apt` packages, that were not needed for the container's functionality. Not only can this change trim your image size but it also can also reduce the attack surface.
- `ca-certificates` was added because it was needed for the `curl` command.
I hope that you find them useful. Please let me know if you have any concerns.
Thank you.

Chore: reduce attack surface and size for Docker image

---

compose/docker-compose.yml

When not using `KONG_PG_DATABASE` default (which is _kong_), the _pg_isready_ command is not working as expected.
Therefore this PR is only to add `-d ${KONG_PG_DATABASE:-kong}` to the healthcheck command.

fix(docker-compose): adding database name to pg_isready

---

Dockerfile.deb
Dockerfile.rpm
build_your_own_images.md
ubuntu/Dockerfile
update.sh

This PR changes the source of `deb` and `rpm` packages from the old [pulp repository](https://download.konghq.com) to the new [cloudsmith repository](https://packages.konghq.com). 
The changes affect the `Dockerfile`s, the documentation and update script.
The Gateway version was also bumped to `3.7.0` in the process.
closes: #700

feat(*): use cloudsmith instead of pulp to download packages

---

ubuntu/Dockerfile

Target file was missing when downloading Kong package for Ubuntu distros, stdouting the contents.

fix(Dockerfile): added missing target file for deb package

---

submit.sh

These changes should ensure that the next time 2.8 is released, it does not include an arm64 variant.
https://konghq.atlassian.net/browse/KAG-4469
Relates to: https://github.com/docker-library/official-images/pull/16962

Fix: Remove arm64 for 2.8

---

Dockerfile.deb
Dockerfile.rpm
ubuntu/Dockerfile

The error is simply due to the missing `luarocks-admin`, which requires installing `luarocks`.
`deb` and `rpm` packages need to be installed from source. Additionally, in the `rpm` environment, `lua-devel` and `readline-devel` cannot be directly installed using `yum`, so they also need to be installed from source.

fix(Dockerfile): install luarocks

---

docker-entrypoint.sh
ubuntu/docker-entrypoint.sh

This adapts the fix from d3411e0 to additionally search $PREFIX/sockets for leftover unix sockets.
See also: https://github.com/Kong/kong/pull/13409 and https://github.com/Kong/kong/issues/13730
[KAG-5691](https://konghq.atlassian.net/browse/KAG-5691)
[KAG-5691]: https://konghq.atlassian.net/browse/KAG-5691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(docker-entrypoint): search new directory for socket cleanup

---

.github/workflows/version2_test.yml

Bump the runner version to the `ubuntu-latest` as `ubuntu-20.04` is retired.
KAG-7154

ci(*): bump runner version to use the ubuntu-latest
