Kong/docker-kong

Dockerfile

```
$ docker images 
less-layers-kong                        latest              ec62529b999a
2 minutes ago       236.6 MB
master-kong                             latest              eae83cf7973e
2 hours ago         368 MB
```

Save layers and disk space

---

compose/README.md
compose/docker-compose.yml
compose/kong/Dockerfile
compose/kong/containerpilot.json
compose/nginx/Dockerfile
compose/nginx/containerpilot.json
compose/nginx/nginx.conf
compose/nginx/nginx.conf.ctmpl
compose/nginx/reload-nginx.sh

Docker compose

---

docker-entrypoint.sh

With the exporting above, the test makes no sense

Delete useless line

---

Dockerfile

Add checksum check to file downloaded in Alpine Dockerfile.

feat(alpine) add checksum check

---

compose/README.md

docs(compose) fixing broken link

---

LICENSE

chore(*) adding license

---

alpine/Dockerfile

Adding support for TZ environment variable in alpine as per #124

Added tzdata Alpine package

---

compose/docker-compose.yml

adding KONG_ADMIN_LISTEN and upgrade to PostfreSQL 9.5

Update docker-compose to be able to work with the last kong release 0.12.1

---

alpine/Dockerfile

Revert "feat(alpine) use https repositories"

---

.travis.yml

feat(ci) add travis

---

compose/docker-compose.yml

- alternative/better solution for pull #189 
- add use of postgres password for db service
- add in some more env vars for kong

Various compose improvements

---

alpine/docker-entrypoint.sh
centos/docker-entrypoint.sh
rhel/docker-entrypoint.sh

See https://github.com/docker-library/official-images/pull/5380#issuecomment-459915214

fix(cli) apply quotes

---

.gitignore
.travis.yml
Makefile
tests.sh

~merge https://github.com/Kong/kong-build-tools/pull/21 first~ done

feat(tests) integrate Kong functional tests from kong-build-tools

---

compose/docker-compose.yml

Updated the compose:
- Bumped compose version to support new functionality
- added network kone-net
- added volume kong_data for DB state

Bumbed compose version, fixed user, and passed all params

---

compose/docker-compose.yml
tests.sh

if the migrations fail we should restart until they succeed

fix(docker-compose) restart the migrations container if it failed

---

alpine/Dockerfile
tests.sh

Fix the test on the `luarocks` command to ensure it fails correctly when luarocks command doesn't work

test(luarocks) correctly test that the luarocks command works

---

swarm/docker-compose.yml
tests.sh

Credit to @OwenJacob ( https://github.com/Kong/docker-kong/issues/224#issue-405632759 )

feat(swarm) include a docker swarm compatible docker-compose file

---

alpine/Dockerfile
centos/Dockerfile
rhel/Dockerfile

chore(*) bump to kong 1.2.0rc1

---

alpine/Dockerfile
centos/Dockerfile
rhel/Dockerfile

chore(*) bump to kong 1.2.0rc2

---

customize/Dockerfile
customize/example.sh
customize/packer.lua
customize/readme.md

Also some minor cosmetic changes and an example.

fix(enterprise) add enterprise license option

---

tests.sh

small adjustments so tests pass on master again

fix(tests)

---

submit.sh

Introduces the flag -f for making releases based on old versions that are not
the current master.

feat(scripts) add -f option for submitting non-master versions

---

.travis.yml
ubuntu/Dockerfile
ubuntu/docker-entrypoint.sh
update.sh

Add ubuntu xenial base image with the ability to build arm64 images.
The Ubuntu tests are allowed to fail at this time because the ubuntu image is not Kong mesh capable

feat(arm64) build Kong ubuntu images including arm64

---

.travis.yml
Makefile
alpine/Dockerfile
centos/Dockerfile
rhel/Dockerfile
tests.sh
ubuntu/Dockerfile

add a Makefile task to release RHEL docker container

feat(rhel) automate the rhel release process

---

alpine/docker-entrypoint.sh
centos/docker-entrypoint.sh
ubuntu/docker-entrypoint.sh

fixes #317 the problem was introduced [here](https://github.com/Kong/docker-kong/commit/2cb3c806f62dbd1a96b537d918ce8512924b7b05#diff-5c73c9eea757330d82ac430a31cd4181L15).

fix(entrypoint) pass parameters when preparing the prefix

---

alpine/Dockerfile

closes https://github.com/Kong/docker-kong/issues/334

chore(dependency) bump the alpine version to 3.11

---

.travis.yml
Makefile
alpine/Dockerfile
alpine/docker-entrypoint.sh
centos/Dockerfile
centos/docker-entrypoint.sh
compose/docker-compose.yml
rhel/Dockerfile
tests.sh
ubuntu/Dockerfile

closes https://github.com/Kong/kong/issues/5708

fix(ocp) fix openshift permissions issue

---

alpine/Dockerfile
centos/Dockerfile
rhel/Dockerfile
ubuntu/Dockerfile

the next minor version of Kong will require zlib https://github.com/Kong/kong/commit/9d830a6e9c38a01c67be5d058d8a1b99170b42e9#diff-2a76b45c239cc30e15f587fc82a8fa61R20

fix(zlib) add zlib as a Kong requirement

---

alpine/Dockerfile
centos/Dockerfile
ubuntu/Dockerfile

closes https://github.com/Kong/docker-kong/issues/359

feat(git) add git to our docker images

---

alpine/Dockerfile
centos/Dockerfile
rhel/Dockerfile
ubuntu/Dockerfile

- remove the kong.tar.gz file from alpine
- add zlib-dev to alpine
- run `kong version` in all Dockerfile's as a check that Kong is correctly installed

fix(various) a few small docker fixes

---

centos/Dockerfile
rhel/Dockerfile

copy of #383 cause I forgot rpm-y Dockerfiles

fix(ee) set EE ASSET for centos and rhel

---

centos/Dockerfile
rhel/Dockerfile
ubuntu/Dockerfile

do not merge until after 2.2.0

chore(ownership) after-install now handles file / directory ownership

---

Makefile
alpine/Dockerfile
update.sh

Also update kbt version in makefile to match kong's -- and add automation to `update.sh`

fix(update) ensure alpine and rhel update correctly

---

Makefile

chore(deps) bump kbt to 4.13.0

---

alpine/docker-entrypoint.sh
centos/docker-entrypoint.sh
rhel/docker-entrypoint.sh
ubuntu/docker-entrypoint.sh

Only set the enviornment variable, if it wasn't set already

fix(entrypoint) allow overriding daemonizing

---

.editorconfig
alpine/Dockerfile
alpine/docker-entrypoint.sh
centos/Dockerfile
centos/docker-entrypoint.sh
rhel/Dockerfile
rhel/docker-entrypoint.sh
submit.sh
tests/04-executables.test.sh
ubuntu/Dockerfile
ubuntu/docker-entrypoint.sh

This allows the Kong container itself to be easier used as a
build container for Kong related tasks.
Adds tests for availability in the path of; luarocks, resty,
nginx, lua, luajit.

feat(*) make core executables available

---

tests/01-image.test.sh
tests/02-customize.test.sh
tests/03-cis-sec.test.sh
tests/04-executables.test.sh
tests/test.sh

This moves in a new version of the `test.sh` file. The test files themselves only get an updated invocation line, at the bottom. No functional changes to the tests.

chore(test) bump the test framework

---

customize/packer.lua
tests/02-customize.test.sh

previously it would always add the injected plugins.

fix(customize) only inject if 'bundled' is provided

---

submit.sh

* Ensure it doesn't swallow the previous version top line.
* Ensure tags are correctly applied.

chore(automation) fix automation for major/minor releases

---

alpine/Dockerfile
centos/Dockerfile
ubuntu/Dockerfile

per https://github.com/docker-library/official-images/pull/11532#issuecomment-996229443 add a Dockerfile comment so our upgrades don't someday accidentally migrate into our official images

chore(comment): add a Dockerfile comment

---

centos/Dockerfile

In order to load new repositories we require a `yum clean`

fix(centos): centos needs a yum clean

---

customize/packer.lua

fix(customize) only a template without plugins failed

---

Dockerfile.apk

chore(apk): remove apk tar gz

---

Dockerfile.apk

https://github.com/Kong/kong/discussions/10278

chore(apk): remove build_deps

---

compose/README.md

Some Compose docs improvements.
Fixes #540.

docs(compose/readme) refactor docs, add version notice

---

Dockerfile.apk

This is a cherry-pick of #637 into the release/3.2.x branch

fix(apk) remove alpine deps
